-- ============================================================================
-- Row-Level Security (RLS) Policies for Muchiri Warehouse System
-- ============================================================================
-- Purpose: Enforce role-based access control at the database level
-- Roles: OWNER, MANAGER, DISTRIBUTOR, CLIENT
-- Created: November 18, 2025
-- Version: 2.0 (PascalCase corrected)
-- ============================================================================
-- IMPORTANT: This version uses PascalCase table and column names to match
-- the actual Supabase schema generated by Prisma
-- ============================================================================

-- ============================================================================
-- 1. USER TABLE
-- ============================================================================

ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;

-- OWNER: Full access to all users
CREATE POLICY "owner_all_users" ON "User"
  FOR ALL
  USING (
    auth.uid() IN (SELECT id FROM "User" WHERE role = 'OWNER')
  );

-- MANAGER: Can view distributors and clients in their warehouse
CREATE POLICY "manager_view_users" ON "User"
  FOR SELECT
  USING (
    auth.uid() IN (
      SELECT "managerId" FROM "WarehouseManager" WHERE "isActive" = true
    )
  );

-- DISTRIBUTOR: Can view their own clients
CREATE POLICY "distributor_view_clients" ON "User"
  FOR SELECT
  USING (
    id IN (
      SELECT c."userId" FROM "Client" c
      JOIN "Distributor" d ON c."distributorId" = d.id
      WHERE d."userId" = auth.uid() AND c."isActive" = true
    )
    OR id = auth.uid()
  );

-- ALL USERS: Can view and update their own record
CREATE POLICY "self_view_users" ON "User"
  FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "self_update_users" ON "User"
  FOR UPDATE
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- ============================================================================
-- 2. WAREHOUSE TABLE
-- ============================================================================

ALTER TABLE "Warehouse" ENABLE ROW LEVEL SECURITY;

-- OWNER: Full access to all warehouses
CREATE POLICY "owner_all_warehouses" ON "Warehouse"
  FOR ALL
  USING (
    auth.uid() IN (SELECT id FROM "User" WHERE role = 'OWNER')
  );

-- MANAGER: Read access to their warehouse
CREATE POLICY "manager_view_warehouses" ON "Warehouse"
  FOR SELECT
  USING (
    auth.uid() IN (
      SELECT "managerId" FROM "WarehouseManager" WHERE "warehouseId" = "Warehouse".id AND "isActive" = true
    )
  );

-- DISTRIBUTOR: Read access to warehouses they're linked to
CREATE POLICY "distributor_view_warehouses" ON "Warehouse"
  FOR SELECT
  USING (
    id IN (
      SELECT wd."warehouseId" FROM "WarehouseDistributor" wd
      JOIN "Distributor" d ON wd."distributorId" = d.id
      WHERE d."userId" = auth.uid() AND wd."isActive" = true
    )
  );

-- ============================================================================
-- 3. WAREHOUSEMANAGER TABLE
-- ============================================================================

ALTER TABLE "WarehouseManager" ENABLE ROW LEVEL SECURITY;

-- OWNER: Full access to manage warehouse managers
CREATE POLICY "owner_all_warehouse_managers" ON "WarehouseManager"
  FOR ALL
  USING (
    auth.uid() IN (SELECT id FROM "User" WHERE role = 'OWNER')
  );

-- MANAGER: Can view their own assignment
CREATE POLICY "manager_view_own_assignment" ON "WarehouseManager"
  FOR SELECT
  USING ("managerId" = auth.uid());

-- ============================================================================
-- 4. PRODUCT TABLE
-- ============================================================================

ALTER TABLE "Product" ENABLE ROW LEVEL SECURITY;

-- OWNER: Full access to all products
CREATE POLICY "owner_all_products" ON "Product"
  FOR ALL
  USING (
    auth.uid() IN (SELECT id FROM "User" WHERE role = 'OWNER')
  );

-- MANAGER: Full access to products
CREATE POLICY "manager_all_products" ON "Product"
  FOR ALL
  USING (
    auth.uid() IN (
      SELECT "managerId" FROM "WarehouseManager" WHERE "isActive" = true
    )
  );

-- DISTRIBUTOR: Read access to active products
CREATE POLICY "distributor_view_products" ON "Product"
  FOR SELECT
  USING (
    "isActive" = true
    AND auth.uid() IN (SELECT "userId" FROM "Distributor" WHERE "isActive" = true)
  );

-- CLIENT: Read access to active products from their distributor's inventory
CREATE POLICY "client_view_products" ON "Product"
  FOR SELECT
  USING (
    "isActive" = true
    AND id IN (
      SELECT di."productId" FROM "DistributorInventory" di
      JOIN "Client" c ON di."distributorId" = c."distributorId"
      WHERE c."userId" = auth.uid() AND c."isActive" = true
    )
  );

-- ============================================================================
-- 5. WAREHOUSEINVENTORY TABLE
-- ============================================================================

ALTER TABLE "WarehouseInventory" ENABLE ROW LEVEL SECURITY;

-- OWNER: Full read access
CREATE POLICY "owner_view_warehouse_inventory" ON "WarehouseInventory"
  FOR SELECT
  USING (
    auth.uid() IN (SELECT id FROM "User" WHERE role = 'OWNER')
  );

-- MANAGER: Full access to warehouse inventory
CREATE POLICY "manager_all_warehouse_inventory" ON "WarehouseInventory"
  FOR ALL
  USING (
    auth.uid() IN (
      SELECT wm."managerId" FROM "WarehouseManager" wm
      WHERE wm."warehouseId" = "WarehouseInventory"."warehouseId" AND wm."isActive" = true
    )
  );

-- DISTRIBUTOR: Read access for ordering purposes
CREATE POLICY "distributor_view_warehouse_inventory" ON "WarehouseInventory"
  FOR SELECT
  USING (
    auth.uid() IN (
      SELECT d."userId" FROM "Distributor" d
      JOIN "WarehouseDistributor" wd ON d.id = wd."distributorId"
      WHERE wd."warehouseId" = "WarehouseInventory"."warehouseId"
        AND wd."isActive" = true
        AND d."isActive" = true
    )
  );

-- ============================================================================
-- 6. DISTRIBUTOR TABLE
-- ============================================================================

ALTER TABLE "Distributor" ENABLE ROW LEVEL SECURITY;

-- OWNER: Full read access
CREATE POLICY "owner_view_distributors" ON "Distributor"
  FOR SELECT
  USING (
    auth.uid() IN (SELECT id FROM "User" WHERE role = 'OWNER')
  );

-- MANAGER: Full access to distributors
CREATE POLICY "manager_all_distributors" ON "Distributor"
  FOR ALL
  USING (
    auth.uid() IN (
      SELECT "managerId" FROM "WarehouseManager" WHERE "isActive" = true
    )
  );

-- DISTRIBUTOR: Can view and update their own record
CREATE POLICY "distributor_view_own" ON "Distributor"
  FOR SELECT
  USING ("userId" = auth.uid());

CREATE POLICY "distributor_update_own" ON "Distributor"
  FOR UPDATE
  USING ("userId" = auth.uid())
  WITH CHECK ("userId" = auth.uid());

-- ============================================================================
-- 7. WAREHOUSEDISTRIBUTOR TABLE
-- ============================================================================

ALTER TABLE "WarehouseDistributor" ENABLE ROW LEVEL SECURITY;

-- OWNER: Full read access
CREATE POLICY "owner_view_warehouse_distributors" ON "WarehouseDistributor"
  FOR SELECT
  USING (
    auth.uid() IN (SELECT id FROM "User" WHERE role = 'OWNER')
  );

-- MANAGER: Full access to manage warehouse-distributor relationships
CREATE POLICY "manager_all_warehouse_distributors" ON "WarehouseDistributor"
  FOR ALL
  USING (
    auth.uid() IN (
      SELECT "managerId" FROM "WarehouseManager"
      WHERE "warehouseId" = "WarehouseDistributor"."warehouseId" AND "isActive" = true
    )
  );

-- DISTRIBUTOR: Read access to their own assignment
CREATE POLICY "distributor_view_own_assignment" ON "WarehouseDistributor"
  FOR SELECT
  USING (
    "distributorId" IN (
      SELECT id FROM "Distributor" WHERE "userId" = auth.uid()
    )
  );

-- ============================================================================
-- 8. CLIENT TABLE
-- ============================================================================

ALTER TABLE "Client" ENABLE ROW LEVEL SECURITY;

-- OWNER: Full read access
CREATE POLICY "owner_view_clients" ON "Client"
  FOR SELECT
  USING (
    auth.uid() IN (SELECT id FROM "User" WHERE role = 'OWNER')
  );

-- MANAGER: Read access to all clients
CREATE POLICY "manager_view_clients" ON "Client"
  FOR SELECT
  USING (
    auth.uid() IN (
      SELECT "managerId" FROM "WarehouseManager" WHERE "isActive" = true
    )
  );

-- MANAGER: Can update clients (for bulk reassignment)
CREATE POLICY "manager_update_clients" ON "Client"
  FOR UPDATE
  USING (
    auth.uid() IN (
      SELECT "managerId" FROM "WarehouseManager" WHERE "isActive" = true
    )
  )
  WITH CHECK (
    auth.uid() IN (
      SELECT "managerId" FROM "WarehouseManager" WHERE "isActive" = true
    )
  );

-- DISTRIBUTOR: Full access to their own clients
CREATE POLICY "distributor_all_clients" ON "Client"
  FOR ALL
  USING (
    "distributorId" IN (
      SELECT id FROM "Distributor" WHERE "userId" = auth.uid()
    )
  );

-- CLIENT: Can view and update their own record
CREATE POLICY "client_view_own" ON "Client"
  FOR SELECT
  USING ("userId" = auth.uid());

CREATE POLICY "client_update_own" ON "Client"
  FOR UPDATE
  USING ("userId" = auth.uid())
  WITH CHECK ("userId" = auth.uid());

-- ============================================================================
-- 9. DISTRIBUTORINVENTORY TABLE
-- ============================================================================

ALTER TABLE "DistributorInventory" ENABLE ROW LEVEL SECURITY;

-- OWNER: Full read access
CREATE POLICY "owner_view_distributor_inventory" ON "DistributorInventory"
  FOR SELECT
  USING (
    auth.uid() IN (SELECT id FROM "User" WHERE role = 'OWNER')
  );

-- MANAGER: Read access to all distributor inventory
CREATE POLICY "manager_view_distributor_inventory" ON "DistributorInventory"
  FOR SELECT
  USING (
    auth.uid() IN (
      SELECT "managerId" FROM "WarehouseManager" WHERE "isActive" = true
    )
  );

-- DISTRIBUTOR: Full access to their own inventory
CREATE POLICY "distributor_all_own_inventory" ON "DistributorInventory"
  FOR ALL
  USING (
    "distributorId" IN (
      SELECT id FROM "Distributor" WHERE "userId" = auth.uid()
    )
  );

-- CLIENT: Read access to their distributor's inventory
CREATE POLICY "client_view_distributor_inventory" ON "DistributorInventory"
  FOR SELECT
  USING (
    "distributorId" IN (
      SELECT "distributorId" FROM "Client" WHERE "userId" = auth.uid() AND "isActive" = true
    )
  );

-- ============================================================================
-- 10. ORDER TABLE
-- ============================================================================

ALTER TABLE "Order" ENABLE ROW LEVEL SECURITY;

-- OWNER: Full read access to all orders
CREATE POLICY "owner_view_all_orders" ON "Order"
  FOR SELECT
  USING (
    auth.uid() IN (SELECT id FROM "User" WHERE role = 'OWNER')
  );

-- MANAGER: Full access to warehouse orders
CREATE POLICY "manager_all_warehouse_orders" ON "Order"
  FOR ALL
  USING (
    "orderType" = 'WAREHOUSE_TO_DISTRIBUTOR'
    AND auth.uid() IN (
      SELECT "managerId" FROM "WarehouseManager"
      WHERE "warehouseId" = "Order"."warehouseId" AND "isActive" = true
    )
  );

-- MANAGER: Read access to distributor-client orders for analytics
CREATE POLICY "manager_view_distributor_orders" ON "Order"
  FOR SELECT
  USING (
    "orderType" = 'DISTRIBUTOR_TO_CLIENT'
    AND auth.uid() IN (
      SELECT "managerId" FROM "WarehouseManager" WHERE "isActive" = true
    )
  );

-- DISTRIBUTOR: Full access to orders they placed (warehouse orders)
CREATE POLICY "distributor_all_warehouse_orders" ON "Order"
  FOR ALL
  USING (
    "orderType" = 'WAREHOUSE_TO_DISTRIBUTOR'
    AND "distributorId" IN (
      SELECT id FROM "Distributor" WHERE "userId" = auth.uid()
    )
  );

-- DISTRIBUTOR: Full access to client orders they receive
CREATE POLICY "distributor_all_client_orders" ON "Order"
  FOR ALL
  USING (
    "orderType" = 'DISTRIBUTOR_TO_CLIENT'
    AND "distributorId" IN (
      SELECT id FROM "Distributor" WHERE "userId" = auth.uid()
    )
  );

-- CLIENT: Can create and view their own orders
CREATE POLICY "client_insert_orders" ON "Order"
  FOR INSERT
  WITH CHECK (
    "orderType" = 'DISTRIBUTOR_TO_CLIENT'
    AND "clientId" IN (
      SELECT id FROM "Client" WHERE "userId" = auth.uid()
    )
  );

CREATE POLICY "client_view_own_orders" ON "Order"
  FOR SELECT
  USING (
    "orderType" = 'DISTRIBUTOR_TO_CLIENT'
    AND "clientId" IN (
      SELECT id FROM "Client" WHERE "userId" = auth.uid()
    )
  );

-- ============================================================================
-- 11. ORDERITEM TABLE
-- ============================================================================

ALTER TABLE "OrderItem" ENABLE ROW LEVEL SECURITY;

-- OWNER: Full read access
CREATE POLICY "owner_view_all_order_items" ON "OrderItem"
  FOR SELECT
  USING (
    auth.uid() IN (SELECT id FROM "User" WHERE role = 'OWNER')
  );

-- MANAGER: Full access to order items for warehouse orders
CREATE POLICY "manager_all_order_items" ON "OrderItem"
  FOR ALL
  USING (
    "orderId" IN (
      SELECT o.id FROM "Order" o
      JOIN "WarehouseManager" wm ON o."warehouseId" = wm."warehouseId"
      WHERE wm."managerId" = auth.uid() AND wm."isActive" = true
    )
  );

-- DISTRIBUTOR: Full access to their order items
CREATE POLICY "distributor_all_order_items" ON "OrderItem"
  FOR ALL
  USING (
    "orderId" IN (
      SELECT o.id FROM "Order" o
      JOIN "Distributor" d ON o."distributorId" = d.id
      WHERE d."userId" = auth.uid()
    )
  );

-- CLIENT: Can insert and view order items for their own orders
CREATE POLICY "client_insert_order_items" ON "OrderItem"
  FOR INSERT
  WITH CHECK (
    "orderId" IN (
      SELECT o.id FROM "Order" o
      JOIN "Client" c ON o."clientId" = c.id
      WHERE c."userId" = auth.uid()
    )
  );

CREATE POLICY "client_view_own_order_items" ON "OrderItem"
  FOR SELECT
  USING (
    "orderId" IN (
      SELECT o.id FROM "Order" o
      JOIN "Client" c ON o."clientId" = c.id
      WHERE c."userId" = auth.uid()
    )
  );

-- ============================================================================
-- 12. PAYMENT TABLE (M-Pesa Payments)
-- ============================================================================

ALTER TABLE "Payment" ENABLE ROW LEVEL SECURITY;

-- OWNER: Full read access
CREATE POLICY "owner_view_all_payments" ON "Payment"
  FOR SELECT
  USING (
    auth.uid() IN (SELECT id FROM "User" WHERE role = 'OWNER')
  );

-- MANAGER: Full access to payments
CREATE POLICY "manager_all_payments" ON "Payment"
  FOR ALL
  USING (
    auth.uid() IN (
      SELECT "managerId" FROM "WarehouseManager" WHERE "isActive" = true
    )
  );

-- DISTRIBUTOR: Can create and view payments for their own orders
CREATE POLICY "distributor_insert_payments" ON "Payment"
  FOR INSERT
  WITH CHECK (
    "orderId" IN (
      SELECT o.id FROM "Order" o
      JOIN "Distributor" d ON o."distributorId" = d.id
      WHERE d."userId" = auth.uid()
    )
  );

CREATE POLICY "distributor_view_own_payments" ON "Payment"
  FOR SELECT
  USING (
    "orderId" IN (
      SELECT o.id FROM "Order" o
      JOIN "Distributor" d ON o."distributorId" = d.id
      WHERE d."userId" = auth.uid()
    )
  );

-- ============================================================================
-- 13. CLIENTPAYMENT TABLE (Manual Tracking)
-- ============================================================================

ALTER TABLE "ClientPayment" ENABLE ROW LEVEL SECURITY;

-- OWNER: Full read access
CREATE POLICY "owner_view_all_client_payments" ON "ClientPayment"
  FOR SELECT
  USING (
    auth.uid() IN (SELECT id FROM "User" WHERE role = 'OWNER')
  );

-- MANAGER: Read access for analytics
CREATE POLICY "manager_view_client_payments" ON "ClientPayment"
  FOR SELECT
  USING (
    auth.uid() IN (
      SELECT "managerId" FROM "WarehouseManager" WHERE "isActive" = true
    )
  );

-- DISTRIBUTOR: Full access to client payments they manage
CREATE POLICY "distributor_all_client_payments" ON "ClientPayment"
  FOR ALL
  USING (
    "distributorId" IN (
      SELECT id FROM "Distributor" WHERE "userId" = auth.uid()
    )
  );

-- CLIENT: Read access to their own payments
CREATE POLICY "client_view_own_payments" ON "ClientPayment"
  FOR SELECT
  USING (
    "clientId" IN (
      SELECT id FROM "Client" WHERE "userId" = auth.uid()
    )
  );

-- ============================================================================
-- 14. INVENTORYTRANSACTION TABLE (Audit Trail)
-- ============================================================================

ALTER TABLE "InventoryTransaction" ENABLE ROW LEVEL SECURITY;

-- OWNER: Full read access
CREATE POLICY "owner_view_all_inventory_transactions" ON "InventoryTransaction"
  FOR SELECT
  USING (
    auth.uid() IN (SELECT id FROM "User" WHERE role = 'OWNER')
  );

-- MANAGER: Full access to all inventory transactions
CREATE POLICY "manager_all_inventory_transactions" ON "InventoryTransaction"
  FOR ALL
  USING (
    auth.uid() IN (
      SELECT "managerId" FROM "WarehouseManager" WHERE "isActive" = true
    )
  );

-- DISTRIBUTOR: Can create and view their own inventory transactions
CREATE POLICY "distributor_insert_inventory_transactions" ON "InventoryTransaction"
  FOR INSERT
  WITH CHECK (
    "distributorId" IN (
      SELECT id FROM "Distributor" WHERE "userId" = auth.uid()
    )
  );

CREATE POLICY "distributor_view_own_inventory_transactions" ON "InventoryTransaction"
  FOR SELECT
  USING (
    "distributorId" IN (
      SELECT id FROM "Distributor" WHERE "userId" = auth.uid()
    )
  );

-- ============================================================================
-- POLICY SUMMARY
-- ============================================================================
-- Total Tables Secured: 14
-- Total Policies Created: 70
--
-- Tables (PascalCase):
-- 1. User (5 policies)
-- 2. Warehouse (3 policies)
-- 3. WarehouseManager (2 policies)
-- 4. Product (4 policies)
-- 5. WarehouseInventory (3 policies)
-- 6. Distributor (3 policies)
-- 7. WarehouseDistributor (3 policies)
-- 8. Client (5 policies)
-- 9. DistributorInventory (4 policies)
-- 10. Order (7 policies)
-- 11. OrderItem (5 policies)
-- 12. Payment (4 policies)
-- 13. ClientPayment (4 policies)
-- 14. InventoryTransaction (4 policies)
--
-- Security Model:
-- - OWNER: Full access to all data (read-only in most cases)
-- - MANAGER: Full access to warehouse operations, distributors, products, inventory
-- - DISTRIBUTOR: Full access to own data, orders, clients, and inventory
-- - CLIENT: Limited to viewing products and managing own orders
--
-- Key Features:
-- - Row-level isolation between roles
-- - Prevents cross-role data access
-- - Supports multi-level supply chain (warehouse -> distributor -> client)
-- - Maintains audit trail integrity
-- - Enables secure M-Pesa payment processing
-- - Protects sensitive business data
--
-- CHANGES FROM v1.0:
-- - All table names updated from snake_case to PascalCase with double quotes
-- - All column names updated from snake_case to camelCase with double quotes
-- - Examples: users -> "User", user_id -> "userId", is_active -> "isActive"
-- - All foreign key references updated to match PascalCase schema
-- - All JOIN conditions updated to use camelCase column names
-- ============================================================================
